### PR TITLE
Fixed links to website

### PR DESCRIPTION
**Pull request by tenchooo**
Fixed links to website.

### CODE REVIEW

**Comment by Vaelatern** [comment]
lgtm, @the-maldridge do you care about the https changes?

**Comment by the-maldridge** [comment]
The website should always be available on https, but I'd rather the link update and the protocol change happen in the same commit.

**Comment by tenchooo** [comment]
Ok so I'll revert changes and do everything in the same commit. Just so we're clear...one commit per file with all the changes or just one commit for all? In the last case wouldn't it be simpler to just create a merge commit on your side?
Let me know.

**Comment by Vaelatern** [comment]
`one commit per file with all the changes`

**Comment by bobertlo** [comment]
bump now that someone else owns voidlinux.eu

**Comment by the-maldridge** [comment]
Superseded by #41

**Pull request closed without merging**
