### PR TITLE
require explicitly listing enabled services

### PR DESCRIPTION
**Pull request by paper42**
Previously all services were enabled with some exceptions. That way some
services got enabled unintentionally when they were added somewhere in
the dependency tree.

This commit requires explicitly listing enabled services with the
exception of DEFAULT_SERVICE_LIST in mklive.sh - agetty-tty1-6, udevd.

difference from the generated images before this commit:
```
plain mklive:  -acpid -dhcpcd -sshd -uuidd
base:          -uuidd
enlightenment: -uuidd -acpid -rtkit
xfce:          -uuidd -acpid -rtkit
mate:          -uuidd -acpid -rtkit
cinnamon:      -uuidd -acpid -rtkit -colord
gnome:         -uuidd -acpid -rtkit -colord -bluetoothd -brltty
lxde:          -uuidd -rtkit
lxqt:          -uuidd -acpid -rtkit
kde:           -uuidd -acpid -bluetoothd -boltd -tcsd
```

All images should be tested to make sure the services that are now disabled were not required.

depends on #265 (merged)

### CODE REVIEW

**Comment by paper42** [comment]
- [x] base
- [ ] gnome (gdm now crashes a few times until it finally works probably because ibus is not starting fast enough)
- [ ] kde
- [ ] enlightenment
- [ ] xfce
- [ ] mate
- [ ] cinnamon
- [ ] lxde
- [ ] lxqt

**Comment by leahneukirchen** [comment]
Should we run acpid to shutdown on power button? or is that done differently these days?

**Comment by paper42** [comment]
> Should we run acpid to shutdown on power button? or is that done differently these days?

I still need to test that. All images built with build-x86-images.sh have either acpid or elogind which should handle this. Only a plain mklive run will now produce an image without acpid just because I wanted to only use elogind without acpid in some images.

This way, mklive generates a minimal bootable iso and users including build-x86-images.sh just add what they want to it. I think this is closer to its goal if I understand it correctly and also is much cleaner - we don't have to have two flags, one for enabling extra services/adding extra packages and one for disabling/removing, we can just add.

It wouldn't be nice if the power button didn't work without acpid, but I will have to test that on real hardware.

**Comment by paper42** [comment]
I finished testing all the isos, so this should be ready for a review. acpid is required for shutdown with a power button, but this PR only removes it from plain mklive, not from the base iso.

cc @the-maldridge

**Comment by the-maldridge** [comment]
Please fix conflicts and re-push.

**Comment by paper42** [comment]
fixed

**Pull request closed without merging**
