### PR TITLE
Fix execution of post install scripts on cross builds

### PR DESCRIPTION
**Pull request by renatoaguiar**
Call register_binfmt before installing packages on mkrootfs.

### CODE REVIEW

**Comment by the-maldridge** [comment]
What is the level of portability for the 'F' flag?  Currently you can with some effort run mklive on another distro's kernels and it will work.

**Comment by renatoaguiar** [comment]
> What is the level of portability for the 'F' flag? Currently you can with some effort run mklive on another distro's kernels and it will work.

Very high. The binfmt_misc implementation supports this flag in any recent kernel version. I checked longterm versions and it is already available in 4.9. The only longterm kernels not supporting it are 4.4 and 3.16.

**Comment by xtraeme** [comment]
I'm curious, why the previous code didn't work? (it worked years ago when I implemented it).

**Comment by xtraeme** [comment]
I'm still not sure if I agree with PR. Because not all users will have >=4.9

**Comment by renatoaguiar** [comment]
> I'm curious, why the previous code didn't work? (it worked years ago when I implemented it).

I don't know, It's been failing for me for a while and that was an easy way I found to fix it. I didn't spend time investigating further, but I agreed that the original implementation should be working too.

**Comment by renatoaguiar** [comment]
@xtraeme It turns out it can be fixed by just adding the missing call to register_binfmt on mkrootfs (second item on the commit message). I updated the PR including that part alone and I'll push a new one with the fix binary enhancement, so we can decide later when to merge it.

**Comment by xtraeme** [comment]
right, this is the real fix... thanks

**Pull request merged**
