### PR TITLE
Dockerfile: reduce size of base-chroot image.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Gottox** [comment]
This breaks consistency checks of the docker image. What's the point of reducing the size further?

**Comment by maxice8** [comment]
On Sun, Apr 07, 2019 at 03:06:36AM -0700, Enno Boland wrote:
> This breaks consistency checks of the docker image. What's the point of reducing the size further?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-mklive/pull/61#issuecomment-480576579

Speeding up downloading the image on Travis

**Comment by Gottox** [comment]
What does is safe in terms of time on travis?

**Comment by the-maldridge** [comment]
The size of the image is roughly halved, so for the image pull which is not cached it should approximately half that time as well.

Is it supported to build in a non C locale?

**Comment by xtraeme** [comment]
This is now possible with xbps-0.58 via noextract configuration keyword.

**Comment by the-maldridge** [comment]
The images need to be reworked.  Closing this for now.

**Pull request closed without merging**
