### PR TITLE
Update splash.png

### PR DESCRIPTION
**Pull request by paper42**
`splash.png` is displayed in grub on boot.

before:
image

after:
image

### CODE REVIEW

**Comment by ahesford** [comment]
This looks much nicer.

I almost never encounter the live-image splash screen, but when I do, it looks like an array reshape with the wrong stride or something.

**Comment by paper42** [comment]
> This looks much nicer.

I will try increasing the resolution and making it 16:9, because now it's pixely and stretched. I hope grub scales it down properly on smaller screens, will test.

> I almost never encounter the live-image splash screen, but when I do, it looks like an array reshape with the wrong stride or something.

the old design looks quite dated, but with this new design (which is just the logo without text with black background) void-artwork will consist of 4 images - 1 logo in 4 variants :(

**Comment by the-maldridge** [comment]
I personally like the old design and its dated feel, but it does make the text in the menu kind of hard to read which I think the new graphic would help with.

As an aside, a lot of void's tooling and project ethos is kind of centered around how a technological horizon I'd put at roughly 2002.  Just because something looks visually off when held up against something like ubuntu or gnome3/4 doesn't mean its not something that isn't stylistically appropriate for Void.

**Comment by Vaelatern** [comment]
I personally would love a higher definition image like the older one, if we are comparing shed colors.

**Comment by paper42** [comment]
> I personally like the old design and its dated feel, but it does make the text in the menu kind of hard to read which I think the new graphic would help with.
> 
> As an aside, a lot of void's tooling and project ethos is kind of centered around how a technological horizon I'd put at roughly 2002. Just because something looks visually off when held up against something like ubuntu or gnome3/4 doesn't mean its not something that isn't stylistically appropriate for Void.

The splash image is the first thing people see (excluding visiting the website). It's blurry, stretched (on most modern screens) and in my opinion ugly. I am not saying it can not be made better, it should be possible to create a design that looks great, but also not modern like this one. I will have to leave it to someone else, because it needs a bit of graphic skill.

**Pull request closed without merging**
