### PR TITLE
build-x86-images.sh.in: remove dropped package econnman.

### PR DESCRIPTION
**Pull request by fosslinux**

### CODE REVIEW

**Comment by hippi777** [comment]
hi there! :) 

if econnman was only modified finally, then why is it still removed from here?

**Comment by the-maldridge** [comment]
@fosslinux @q66 in the future cross reference to the PR or commit where the package is dropped.

**Comment by hippi777** [comment]
https://github.com/void-linux/void-packages/pull/25994

**Comment by fosslinux** [comment]
@the-maldridge got it

**Pull request merged**
