### PR TITLE
make it explicit to use the network-legacy dracut module

### PR DESCRIPTION
**Pull request by LaszloGombos**

### CODE REVIEW

**Comment by LaszloGombos** [comment]
Can somebody help please and confirm that https://github.com/void-linux/void-mklive/pull/297 cause no regression (using the current dracut-v053 version ? 

The is a more future-proof way to configure dracut for void and should enable updating to dracut v56 as well.

I hope this is helpful to make some progress on https://github.com/void-linux/void-mklive/issues/296

**Comment by ahesford** [comment]
This is probably not the right fix for a few of reasons:
1. The general-purpose `network` package is supposed to do the right thing. The problem here is that newer `dracut` ships a `network-manager` module that has a `systemd` dependency. If Void is going to ship the `network-manager` module are part of its `dracut` package, tht module should always work. We shouldn't be patching around a Void packaging problem here.
2. There is no *fundamental* reason that the mklive modules can't use an arbitrary network configuration. If the live image has a specific reason to favor `network-legacy` over the `network-manager` preference, a better way to do this is by amending the dracut *configuration*, not the module dependencies:
   ```bash
   add_dracutmodules+=" network-legacy "
   omit_dracutmodules+=" network-manager "
   ```
3. Eventually, I think Dracut is going to abandon `network-legacy` in favor of something like an `iwd` module. If we hard-depend on `network-legacy` here, we'll eventually forget about it and there will be another `dracut` upgrade that breaks this project.

Should Void update `dracut` again, we need to be more careful about scrubbing systemd dependencies. That means either
- Patching the `dbus-daemon` module to eliminate systemd, or
- Dropping all modules on the branch of the dependency graph that depend on `dbus` and its incompatible helpers.
However, given the ongoing and recurrent problems with Dracut embracing systemd, I think we should just freeze our package at 053 indefinitely. If somebody has a compelling need to update, let that person document the need and provide evidence that the update won't subtly break.

**Comment by LaszloGombos** [comment]
> There is no fundamental reason that the mklive modules can't use an arbitrary network configuration. 

https://github.com/dracutdevs/dracut/commit/112f03f9e225a790cbc6378c70773c6af5e7ee34 is the commit that added dbus dracut module dependency to network-manager dracut module.

According to the commit log

> once NM has quit, dynamic addresses can expire if the initrd setup takes longer than the
> DHCP lease interval or than the IPv6 address lifetime.

If live image is using network-manager than life image would have this bug unless it is fixed by some other means.

**Comment by ahesford** [comment]
That's not a fundamental reason that this project should select `network-legacy` over `network` in its own modules. If Void wants to update Dracut, the fix is to either patch out that commit or remove the `network-manager` module in its entirety. Either way, mklive doesn't need to know or care what the `network` module is choosing as the backend.

**Comment by ahesford** [comment]
This is not the place to discuss any of these matters. File an issue in void-packages to discuss a broken `network` module in dracut.

**Pull request closed without merging**
