### PR TITLE
Add support for Pinephone (pinephone)

### LINKED ISSUE #119: Pinephone Support
I've been working on supporting the Pinephone. I can already build a working image.

Similarly to the PBP issue, this one exists to track my progress on this and to bring attention to it so that anyone else wishing to get voidlinux working on the pinephone can re-use my existing work.

- [x] Voidlinux builds and runs
- [ ] Package templates
  - [x] Uploaded to public [repo](https://github.com/EliteTK/void-packages/tree/pinephone) \*
  - [ ] Conform to contributing standards
  - [ ] Merged
- [ ] void-mklive
  - [x] Uploaded to public [repo](https://github.com/EliteTK/void-mklive/tree/pinephone) \*
  - [ ] Merged

\* Note: I am going to push -f to these branches. Just so everyone is aware ahead of time.

I have some questions which I don't know the answers to:

- Where do I get the config file for the bluetooth firmware for the pinephone? The source for the firmware has a file for the pinebookpro but nothing for the pinephone.
- Does CC need to be exported for makefiles which rely on it? cc is not a symlink when I try to build which is odd to me. The pinebookpro u-boot package doesn't set CC and supposedly builds so I'm confused why my u-boot would need this.
- The pinebookpro u-boot package doesn't flash the u-boot either as a kernel config hook or as some kind of postinstall, how should this be handled?
  > Flashing is done by mkimage when the image is built. u-boot images are installed to /boot, so they have to be flashed manually after upgrades. To make it easier, I think we should just provide some tool to flash them to correct place (analagous to grub-install) and document it's use. Updates to u-boot images are not very frequent anyway.
- The pinebookpro mkimage does an xbps-reconfigure in the chroot as part of the image making process to re-generate the u-boot boot.scr but it looks like this already happens in mkplatformfs.sh, is this necessary?
  > Partition UUIDs are only known on mkimage step, so reconfigure is needed to update configuration with correct UUIDs.

Feel free to report issues to the issue trackers in the respective repositories and I'll have a look at them, or just post comments here.

Contributions are welcome but I'm not sure if they won't have to be squashed. If people have suggestions it would be easier to just tell me what I should do and I'll credit the person in the commit message.

Footnote: Bear with me, I don't know what I'm doing, I'm not a maintainer.

### PR DESCRIPTION
**Pull request by jjsullivan5196**
Support for creating a pinephone platformfs and live image. Resolves #119

### CODE REVIEW

**Comment by nadiadavis** [comment]
Works for me with #149 also cherry picked

**Comment by MungFuSensei** [comment]
Can also confirm that this works.

**Comment by the-maldridge** [comment]
@jjsullivan5196 can you resolve conflicts?  I'd like to finish review/merge on this this week if possible.

**Comment by jjsullivan5196** [comment]
@the-maldridge conflicts are fixed :+1:

**Pull request closed without merging**
