### PR TITLE
Add rockpro64 to image builder

### PR DESCRIPTION
**Pull request by tsndqst**
Add support for rockpro64 platform

Based on @tiemenwerkman's work on https://github.com/void-linux/void-mklive/pull/221 and comments from @CameronNemo 
Intended to be used with packages from https://github.com/void-linux/void-packages/pull/33556

### CODE REVIEW

**Comment by CameronNemo** [comment]
LGTM

**Comment by Anachron** [comment]
@CameronNemo @maldridge maybe we can announce it on a blog post after both PRs are merged?

**Comment by Anachron** [comment]
^ A very welcome change to increase the `/boot` size!

**Comment by tsndqst** [comment]
I haven't tested this latest commit yet but I wanted to get the merge conflicts cleared up.

I ran into the space issue on my rp64s so i think increasing the /boot size is due.

**Comment by Anachron** [comment]
Thanks, I am still running this PR with linux6.5 in my rockpro64.

**Pull request merged**
