### PR TITLE
mkrootfs.sh.in: Mention ppc-musl

### PR DESCRIPTION
**Pull request by stenstorp**
Mention ppc-musl in the list of supported architectures.

### CODE REVIEW

**Comment by Vaelatern** [comment]
Is it, @q66?

**Comment by Vaelatern** [comment]
Well, we include i686-musl too, and that doesn't work so I suppose so.

**Comment by stenstorp** [comment]
I've tested it a bunch. Works pretty well.

**Comment by q66** [comment]
related to that, i've had this up for a while https://github.com/void-linux/void-mklive/pull/26

**Pull request merged**
